server:
  port: 8082
spring:
  application:
    name: api-gateway
zuul:
  routes:
    oscar:
      url: http://localhost:8081
#      path: /api/v1/oscars/**
#      serviceId: oscar-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost