openapi: 3.0.3
info:
  title: Oscar service REST endpoints
  description: Additional operations related to calling the API of the first service for SOA Lab1
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api/v1/oscar'
paths:
  /directors/get-loosers:
    get:
      summary: Get a list of directors whose films have not won any Oscars
      description: Get a list of directors whose films have not won any Oscars
      operationId: getDirectorsLoosers
      tags:
        - Oscars
      responses:
        '200':
          description: Returns a list of directors whose films have not won any Oscars
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/LoosersResponseList"
        '414':
          description: URI is too long
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error414"
        '429':
          description: Too Many Requests
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error429"
        '503':
          description: External Service Unavailable
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error503"
        default:
          description: Returns error code, message and time
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
  /movies/honor-by-length/{min-length}/oscars-to-add:
    patch:
      summary: Additionally award all films with a duration longer than the specified number of Oscars
      description: Additionally award all films with a duration longer than the specified number of Oscars
      operationId: awardAllFilmsWithDurationLonger
      tags:
        - Oscars
      parameters:
        - name: min-length
          in: path
          required: true
          description: Minimal duration to award (minutes)
          schema:
            type: integer
            format: int32
            nullable: false
            minimum: 1
            example: 1
      responses:
        '200':
          description: Returns honored movies
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/MoviesHonoredByLengthResponse"
        '400':
          description: Bad Request
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error400"
        '404':
          description: Not Found
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error404"
        '414':
          description: URI is too long
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error414"
        '429':
          description: Too Many Requests
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error429"
        '503':
          description: External Service Unavailable
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error503"
        default:
          description: Returns error code, message and time
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
    
components:
  schemas:
    MovieGenre:
      type: string
      enum:
        - ACTION
        - MUSICAL
        - ADVENTURE
        - FANTASY
      nullable: true
      example: ACTION
    MpaaRating:
      type: string
      enum:
        - G
        - PG
        - R
        - NC_17
      nullable: true
      example: G
    Color:
      type: string
      enum:
        - BLACK
        - YELLOW
        - ORANGE
        - WHITE
      nullable: true
      example: BLACK
    Country:
      type: string
      enum:
        - UNITED_KINGDOM
        - FRANCE
        - SPAIN
        - INDIA
      nullable: true
      example: UNITED_KINGDOM
    LoosersResponseList:
      type: object
      properties:
        pearsons:
          type: array
          items:
            type: object
            required:
              - name
              - height
            properties:
              name:
                type: string
                nullable: false
                minLength: 1
                example: Andrey
              birthday:
                type: string
                format: date
                nullable: true
                example: 2024-09-13
              height:
                type: number
                format: float
                minimum: 0
                nullable: false
                example: 180
              hairColor:
                $ref: "#/components/schemas/Color"
              nationality:
                $ref: "#/components/schemas/Country"
            xml:
              name: pearson
          xml:
            wrapped: true
            name: pearsons
    Person:
      type: object
      required:
        - name
        - height
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
          example: Andrey
        birthday:
          type: string
          format: date
          nullable: true
          example: 2024-09-13
        height:
          type: number
          format: float
          minimum: 0
          nullable: false
          example: 180
        hairColor:
          $ref: "#/components/schemas/Color"
        nationality:
          $ref: "#/components/schemas/Country"
    Coordinates:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: number
          format: double
          nullable: false
          example: 1.1
        y:
          type: integer
          format: int32
          nullable: false
          example: 2
    MoviesHonoredByLengthResponse:
      type: object
      properties:
        movies:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
                nullable: false
                minimum: 1
                example: 1
              name:
                type: string
                nullable: false
                minLength: 1
                example: Interstellar
              coordinates:
                $ref: "#/components/schemas/Coordinates"
              creationDate:
                type: string
                format: date-time
                nullable: false
                example: 2024-09-13T00:00:13
              oscarsCount:
                type: integer
                format: int64
                nullable: false
                minimum: 1
                example: 1
              genre:
                $ref: "#/components/schemas/MovieGenre"
              mpaaRating:
                $ref: "#/components/schemas/MpaaRating"
              screenwriter:
                $ref: "#/components/schemas/Person"
              duration:
                type: integer
                format: int64
                nullable: false
                minimum: 1
                example: 1
            xml:
              name: movie
          xml:
            wrapped: true
            name: movies
    Error:
      xml:
        name: Error
      type: object
      required:
        - message
        - time
      properties:
        message:
          type: string
          example: Internal server error
        time:
          type: string
          format: date-time
          example: 2024-09-13T00:00:13
    Error400:
      xml: 
        name: Error
      type: object
      required:
        - message
        - invalidFields
        - time
      properties:
        message:
          type: string
          example: Bad Request
        invalidFields:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: min-length
              reason:
                type: string
                example: min-length must be a positive number in minures
            xml:
              name: invalidField
          xml:
            wrapped: true
            name: invalidFields
        time:
          type: string
          format: date-time
          example: 2024-09-13T00:00:13
    Error404:
      xml: 
        name: Error
      type: object
      required:
        - message
        - time
      properties:
        message:
          type: string
          example: Not Found
        time:
          type: string
          format: date-time
          example: 2024-09-13T00:00:13
    Error414:
      xml: 
        name: Error
      type: object
      required:
        - message
        - time
      properties:
        message:
          type: string
          example: URI is too long
        time:
          type: string
          format: date-time
          example: 2024-09-13T00:00:13
    Error429:
      xml: 
        name: Error
      type: object
      required:
        - message
        - time
      properties:
        message:
          type: string
          example: Too Many Requests
        time:
          type: string
          format: date-time
          example: 2024-09-13T00:00:13
    Error503:
      xml: 
        name: Error
      type: object
      required:
        - message
        - time
      properties:
        message:
          type: string
          example: External Service Unavailable
        time:
          type: string
          format: date-time
          example: 2024-09-13T00:00:13