spring:
  application:
    name: oscar-service
  ssl:
    bundle:
      pem:
       client:
          truststore:
            certificate: mytruststore.p12
server:
  port: 9797
#  ssl:
#    trust-store: classpath:keystore/mytruststore.p12
#    trust-store-password: changeit

##spring.datasource.url=jdbc:postgresql://localhost:5432/studs
##spring.datasource.username=
##spring.datasource.password=
#spring.datasource.url=jdbc:postgresql://localhost:5435/postgres
#spring.datasource.username=postgres
#spring.datasource.password=athyfylj
#spring.jpa.show-sql=true
#spring.jpa.database=postgresql
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
#spring.mvc.pathmatch.matching-strategy=ant_path_matcher
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#server.error.whitelabel.enabled=false
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.web.resources.add-mappings=false
#server.error.path=/error
#server.port=8088
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=password
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=mycertificate
#server.ssl.enabled=true
#server.ssl.trust-store=classpath:trust_store.p12
#server.ssl.trust-store-password=password
#server.ssl.trust-store-type=PKCS12


