logging:
  level:
    com.anvisero.movieservice: DEBUG
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
server:
  port: 8765
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/baeldung.p12
#    key-store-password: 123456
#    key-alias: baeldung
#    enabled: true

spring:
  application:
    name: movie-service
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
#    username: soa
#    password: soa
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  data:
    jpa:
      repositories:
        bootstrap-mode: default