CREATE TABLE IF NOT EXISTS coordinates
(
    coordinate_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x             DOUBLE PRECISION                        NOT NULL,
    y             INTEGER                                 NOT NULL,
    CONSTRAINT pk_coordinates PRIMARY KEY (coordinate_id)
);

CREATE TABLE IF NOT EXISTS screenwriters
(
    screenwriter_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            TEXT                                    NOT NULL,
    birthday        DATE,
    height          REAL                                    NOT NULL,
    hair_color      VARCHAR(255),
    nationality     VARCHAR(255),
    CONSTRAINT pk_screenwriters PRIMARY KEY (screenwriter_id)
);

CREATE TABLE IF NOT EXISTS movies
(
    movie_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            TEXT                                    NOT NULL,
    coordinate_id   BIGINT                                  NOT NULL,
    creation_date   TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    oscars_count    BIGINT,
    genre           VARCHAR(255)                            NOT NULL,
    mpaa_rating     VARCHAR(255)                            NOT NULL,
    screenwriter_id BIGINT,
    duration        INTEGER                                 NOT NULL,
    CONSTRAINT pk_movies PRIMARY KEY (movie_id),
    CONSTRAINT fk_movies_on_coordinates FOREIGN KEY (coordinate_id) REFERENCES coordinates (coordinate_id) ON DELETE CASCADE,
    CONSTRAINT fk_movies_on_screenwriters FOREIGN KEY (screenwriter_id) REFERENCES screenwriters (screenwriter_id) ON DELETE CASCADE
);
